export const USER = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT: 'LOGOUT',
	REGISTER_REQUEST: 'REGISTER_REQUEST',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAILURE: 'REGISTER_FAILURE',
};

export const ORDER = {
	ORDER_REQUEST: 'ORDER_REQUEST',
	ORDER_SUCCESS: 'ORDER_SUCCESS',
	ORDER_FAILURE: 'ORDER_FAILURE',
	GET_MENU_REQUEST: 'GET_MENU_REQUEST',
	GET_MENU_SUCCESS: 'GET_MENU_SUCCESS',
	GET_MENU_FAILURE: 'GET_MENU_FAILURE',
}