version: '2'

services:
  db:
    container_name: "${APP_NAME}_db"
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql/data/:/var/lib/mysql
    ports:
      - 4567:3306

  backend:
    container_name: "${APP_NAME}_backend"
    build: backend
    command: sh -c 'npm install && npm start'
    volumes:
      - ../:/var/www/
    env_file:
      - ../.env
    depends_on:
      - db

  web-srv:
    container_name: "${APP_NAME}_web-srv"
    image: nginx:alpine
    volumes:
      - ./nginx/configs/conf.d/:/etc/nginx/conf.d/
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - backend
    ports:
      - ${WEB_SRV_PORT}:80
