version: '2'

services:
  db:
    image: mysql:8
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

  php:
    build:
      context: php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony
      - ./docker/logs/php:/var/www/symfony/app/logs
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      APP_ENV: ${ENVIRONMENT}
      APP_SECRET: ${SYMFONY_APP_SECRET}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}

  nginx:
    build: nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx

  elk:
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./docker/elk/logstash:/etc/logstash
      - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - nginx

