version: '3.3'
services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql/dump/:/docker-entrypoint-initdb.d

  wordpress:
    build: ./php
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'JETPACK_DEV_DEBUG', ( 'local' === ${ENV} || 'dev' === ${ENV} ) );
        if ( file_exists( __DIR__ . '/wp-content/vip-config/vip-config.php' ) ) {
            require_once( __DIR__ . '/wp-content/vip-config/vip-config.php' );
        }
        define( 'DISALLOW_FILE_EDIT', true );
        define( 'DISALLOW_FILE_MODS', true );
        define( 'AUTOMATIC_UPDATER_DISABLED', true );
    volumes:
      - ./src:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
